name: arbor-dev
store: /user-environment
system: hohgant
spack:
  repo: https://github.com/spack/spack.git
  commit: v0.19.0
mirror:
  key: /scratch/e1000/bcumming/secret/spack-key.gpg
  enable: true
